# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 05:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodhubinit', '0002_auto_20170701_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=list, null=True, size=None),
        ),
    ]
